# Generated by Django 2.1.7 on 2019-05-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll_ans',
            name='ans_text',
            field=models.CharField(default='dummy-ans', max_length=20),
        ),
    ]
