# Generated by Django 2.1.7 on 2019-05-03 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll_webapp', '0002_poll_ans_ans_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll_options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(default='a', max_length=28)),
            ],
        ),
        migrations.CreateModel(
            name='Poll_votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_voted', models.DateTimeField(default=django.utils.timezone.now)),
                ('ans_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll_webapp.Poll_options')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='poll_ans',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='poll_ans',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='options',
        ),
        migrations.DeleteModel(
            name='Poll_ans',
        ),
        migrations.AddField(
            model_name='poll_options',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll_webapp.Poll'),
        ),
    ]
